Invite-Anyone - CloudSponge features improvements
boonebgorges/invite-anyone pull request #166
Opened 2020-12-09 18:51 UTC by dimitarangelkov

@boonebgorges I think these improvements are safe to be merged with your version of the plugin.

Here are the related issues

- Allow users to enable only the address book providers that they want
- Add an option to enable deep links
- Display the Proxy URL value

2020-12-09 18:52 UTC, boonebgorges commented
Thanks for the PR. I'll review in the next week.

2020-12-10 16:51 UTC, boonebgorges requested changes
Thanks for the PR! This looks mostly good. My main concern is about how the source list is generated and used throughout. See my inline comments.

2020-12-10 16:51 UTC, boonebgorges commented on admin/admin-panel.php
> +	$cloudsponge_sourcesList['gmail'] = array("title"=>"Google Contacts");
Do these names change in different languages? If so, we can either run them through a WordPress internationalization function (so that Invite Anyone translators will have the opportunity to provide translations) or perhaps we can get CS's translations (assuming you keep any and make them available via API)

2020-12-10 16:51 UTC, boonebgorges commented on admin/admin-panel.php
> +						<td><input type="text" style="width: 80%" id="cloudsponge-proxy" name="invite_anyone[cloudsponge_proxy]" value="<?php echo plugins_url() . '/invite-anyone/by-email/cloudsponge-proxy.html' ?>" /
Putting this into an `input` makes it look like it should be editable, which is not the case. See https://stackoverflow.com/questions/38149521/make-html-input-area-readonly-but-selectable for a possible workaround.

2020-12-10 16:51 UTC, boonebgorges commented on admin/admin-panel.php
> +									print '<li><input type="checkbox" name="csSources" value="'.$key.'" '.((in_array($key, $cloudsponge_sources_arr) || $cloudsponge_sources == '')?'checked':'').'> '.$val['title'].'</li>';
For WP security best practices and improved readability, I'd like to request a few changes to this line:

```php
$source_is_checked = in_array( $key, $cloudsponge_sources_arr, true ) || $cloudsponge_sources == '';
print '<li><input type="checkbox" name="csSources" value=" . esc_attr( $key ) . " ' . checked( $source_is_checked, true, false ) . '> ' . esc_html( $val['title'] ) . '</li>';
```

2020-12-10 16:51 UTC, boonebgorges commented on admin/admin-panel.php
> +							<input type="hidden" name="invite_anyone[cloudsponge_sources_list]" value='<?php echo json_encode($cloudsponge_sourcesList); ?>'>
Is there a reason why this list is being sent with the form here, and then used to populate the `sources_list` when building the form on the front end? Is there a situation where we should be storing the source list in the database - either a case where it will be editable by the admin, or where the version should be out of sync with the list on the CS servers? If hardcoding is the best way to provide this list (see `$cloudsponge_sourcesList` above) then let's use that here too. Create a method `CloudSponge_Integration::sources_list()` or something like that and use it in both places. (Bonus: If you decide later to make this information available via API, so that we don't have to hardcode it, we'll have a single place where the swapout can be made.)

Whatever we decide, storing this info in the database seems like a bad idea to me, as it's not dynamic and is subject to corruption/loss.

2020-12-10 16:51 UTC, boonebgorges commented on by-email/cloudsponge-integration.php
> +			$sourcesDisplay[] = '<a class="cloudsponge-launch" data-cloudsponge-source="'.$source.'">'.$sourcesList[$source]["title"].'</a>';
Similar to above, we must escape dynamic values, especially if we continue to pull them from the database:

```php
$sourcesDisplay[] = '<a class="cloudsponge-launch" data-cloudsponge-source="' . esc_attr( $source ) . '">' . esc_html( $sourcesList[ $source ]['title'] ) . '</a>';
```

2020-12-17 09:09 UTC, dimitarangelkov commented on admin/admin-panel.php
> +	$cloudsponge_sourcesList['gmail'] = array("title"=>"Google Contacts");
The sources names don't change, these are brand / product names that don't need translation. Unfortunately CloudSponge doesn't have that API available yet, so for now we have to hardcode them. Once there is an API we can update the plugin.

2020-12-17 09:23 UTC, dimitarangelkov commented on admin/admin-panel.php
> +							<input type="hidden" name="invite_anyone[cloudsponge_sources_list]" value='<?php echo json_encode($cloudsponge_sourcesList); ?>'>
Hardcoding the available sources list is not the best way that's for sure, unfortunately the only available for now. As for the stored data in the database, this is related with the option to select which sources you want to enable for your application. All this data has to be stored in the wordpress and passed as parameters to the CloudSponge widget in order to take effect.

2020-12-18 16:34 UTC, boonebgorges commented on admin/admin-panel.php
> +							<input type="hidden" name="invite_anyone[cloudsponge_sources_list]" value='<?php echo json_encode($cloudsponge_sourcesList); ?>'>
If this information is not editable by the user, then it shouldn't be stored in the database. See https://github.com/boonebgorges/invite-anyone/commit/f6784216414a9a5b15fea793900485c415ad33e7 for an example of how it might work instead. ('sources' - the options *checked* by the user - is of course still stored in the database; it's just the larger list of all CS sources that doesn't need to be stored in this way).

2020-12-24 13:46 UTC, dimitarangelkov commented on admin/admin-panel.php
> +							<input type="hidden" name="invite_anyone[cloudsponge_sources_list]" value='<?php echo json_encode($cloudsponge_sourcesList); ?>'>
Agreed. Definitely as a static function looks better. In the meantime my colleagues from CloudSponge prepared a simple web service that will deliver the full list of sources, so we can get rid of the hardcoded sources.

2021-02-02 18:20 UTC, dimitarangelkov commented
hey @boonebgorges, please review the latest updates.
We've added some copy changes to the CloudSponge Admin Tab. I guess you'll take care for the transportation files.
Thanks for your time and support

2021-02-02 21:09 UTC, boonebgorges commented
Thanks for the changes. There are some problems with the way that translations are implemented, but I will fix them myself after merge.

A question for the CS team: 7722df0 has us fetch the "sources list" from https://api.cloudsponge.com/services.json on every pageload. This only happens on the settings page, so it's likely to be pretty infrequent. But still, under normal circumstances, I would try to cache external API requests for at least a little bit of time. Do you want some caching built into IA here or is it OK to call the endpoint each time? cc @dangerouse  @circuitfive

2021-02-02 22:13 UTC, boonebgorges commented
Scratch my last question. I see now that the `services.json` list is needed on the front end as well, so I have gone ahead and implemented one-hour-expiration caching. This TTL can be adjusted upward if your team wants to reduce bandwidth.

See https://github.com/boonebgorges/invite-anyone/tree/pull-166 for my changes. Your team may want to do a check locally to ensure that things are working as expected before I merge and release.

2021-02-03 05:48 UTC, dimitarangelkov commented
Just updated and checked locally the latest tweaks. All good.

2021-02-04 22:28 UTC, boonebgorges commented
Thanks very much. I've merged from my own copy of the branch.

Does your team have more changes to request at this time? If not, I'll do a release in the upcoming days.

2021-02-05 06:13 UTC, dimitarangelkov commented
We are done for now. You can go ahead with the release.

2021-02-09 23:49 UTC, dangerouse commented
> Thanks very much. I've merged from my own copy of the branch.
> 
> Does your team have more changes to request at this time? If not, I'll do a release in the upcoming days.

@boonebgorges This is awesome! I'm excited to test out the newly published version and start asking our customers to update. Please, let me know if I can do anything to help with that.

2023-09-18 15:53 UTC, closed without merging